name: "Commit Test"

on:
  push:
    branches: [ "master" ]
    # branches:
    #     - "**"

env:
  CGO_ENABLED: 0

jobs:
  go_test_all:
    name: "go build && go test"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ "1.21.x", "1.22.x" ] # we support the latest 2 stable versions of Go
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
      - run: go version
      - name: Build and Test
        run:  |
          go build -v ./...
          go test -v ./...

  tinygo_build_min:
    name: "Build minimal tinygo ${{ matrix.build.name }} example"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        build: [ 
          { name: "plain", build-with: "tinygo build -o plain.wasm -target=wasi ./tinygo/v0/examples/plain/" },
        ]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.21.x"
      - uses: acifani/setup-tinygo@v2
        with:
          tinygo-version: '0.30.0'
      - name: Run build command
        run: ${{ matrix.build.build-with }}
